jobs:
  - job: TestsOnAgent1
    pool: SelfHostedPoolDck
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean test'
          options: '-Dsurefire.suiteXmlFiles=src/test/resources/suites/testng-part1.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/testng-results.xml'

  - job: TestsOnAgent2
    pool: SelfHostedPoolDck
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean test'
          options: '-Dsurefire.suiteXmlFiles=src/test/resources/suites/testng-part2.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/testng-results.xml'
