trigger:
- main

pool: SelfHostedPoolDck

strategy:
  matrix:
    agent1:
      MAVEN_OPTS: "-Dsurefire.suiteXmlFiles=testng-part1.xml"
    agent2:
      MAVEN_OPTS: "-Dsurefire.suiteXmlFiles=testng-part2.xml"
  maxParallel: 2

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '$(MAVEN_OPTS)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/testng-results.xml'
