trigger:
- main

pool:
  name: 'SelfHostedPoolDck'
  demands:
    - java
    - maven

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'

  # ✅ Publish Extent Reports as pipeline artifacts
- task: PublishPipelineArtifact@1
  displayName: 'Publish Extent HTML Report'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/Reports'  # folder where your Extent reports are generated
    artifact: 'ExtentReports'

# ✅ (Optional) Publish report inside pipeline summary tab
# Requires "HTML Report" Azure DevOps extension installed from Marketplace
- task: PublishHTMLReport@1
  displayName: 'Publish Extent Report Tab'
  inputs:
    reportDir: '$(System.DefaultWorkingDirectory)/Reports'
    reportTitle: 'Extent Report'
    tabName: 'Test Report'